Improvement/ - grouping for multiple selections and other bug fixes
rocketium/react-alignment-guides pull request #140
Opened 2022-08-31 09:58 UTC by RocketierYashank

2022-09-08 10:07 UTC, FreakPirate requested changes
Logic and implementations looks pretty clean @Yashank18 @prabhatkadam18 👏 Well done. Try and explain states as comment and see if we can prevent disabling linter.

2022-09-08 12:09 UTC, prabhatkadam18 commented on src/AlignmentGuides.js
> +/* eslint-disable */
Oh, this was a miss, we disabled it as we were working by copying these changes in pando itself and there was basically an error on every line. Will remove this.

2022-09-09 02:38 UTC, somyarocketium approved these changes

2022-09-09 04:55 UTC, FreakPirate approved these changes
LGTM. Approving 👍

2022-09-09 06:28 UTC, merged